[project]
name = "cyberyozh-open-scraper"
version = "0.1.0"
description = "Web Scraper API on Playwright with CyberYozh proxy integration"
authors = [
    { name = "CyberYozh" }
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10,<3.14"


[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
